// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens
WHERE token = $1
    AND NOW() < expires_at
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const newToken = `-- name: NewToken :exec
INSERT INTO refresh_tokens (
    token,
    created_at,
    updated_at
    ,user_id
    ,expires_at
) VALUES (
    $1
    ,NOW()
    ,NOW()
    ,$2
    ,NOW() + INTERVAL '60 days'
)
`

type NewTokenParams struct {
	Token  string
	UserID uuid.NullUUID
}

func (q *Queries) NewToken(ctx context.Context, arg NewTokenParams) error {
	_, err := q.db.ExecContext(ctx, newToken, arg.Token, arg.UserID)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_tokens
SET 
    revoked_at = NOW(),
    updated_at = NOW() + INTERVAL '60 days'
WHERE token = $1
`

func (q *Queries) UpdateRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, token)
	return err
}
